# Generated by Django 4.1.7 on 2023-02-26 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_location_user_locations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['id'], 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
    ]
